#!/bin/bash

action="$1"
addr="$2"
pubif=eth0

if [[ "${addr//:/}" == "$addr" ]]
then
    # not an ipv6 address
    exit
fi

case "$action" in
    add|update)
        ip neigh replace proxy "$addr" dev "$pubif"
        ;;
    delete)
        ip neigh del proxy "$addr" dev "$pubif"
        ;;
esac
